### ISSUE TITLE
The "path" argument must be of type string (v2.4.0)

### ISSUE THREAD

**Issue by kayluhb** [formatjs/babel-plugin-react-intl#135]
When upgrading to 2.4.0 after a fresh checkout of the [RSK](https://github.com/kriasoft/react-starter-kit/tree/feature/react-intl), I receive the following error:

```js
extractMessages: In src/store/logger/logger.server.js:
 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.extname (path.js:1454:5)
    at PluginPass.post (/Users/kayluhb/Projects/react-starter-kit/node_modules/babel-plugin-react-intl/lib/index.js:208:51)
    at transformFile (/Users/kayluhb/Projects/react-starter-kit/node_modules/@babel/core/lib/transformation/index.js:116:26)
    at runSync (/Users/kayluhb/Projects/react-starter-kit/node_modules/@babel/core/lib/transformation/index.js:35:3)
    at transformSync (/Users/kayluhb/Projects/react-starter-kit/node_modules/@babel/core/lib/transform-sync.js:15:38)
    at transform (/Users/kayluhb/Projects/react-starter-kit/node_modules/@babel/core/lib/transform.js:20:65)
    at _callee4$ (/Users/kayluhb/Projects/react-starter-kit/tools/messages.js:122:22)
    at tryCatch (/Users/kayluhb/Projects/react-starter-kit/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/kayluhb/Projects/react-starter-kit/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/kayluhb/Projects/react-starter-kit/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/kayluhb/Projects/react-starter-kit/tools/messages.js:24:221)
    at _next (/Users/kayluhb/Projects/react-starter-kit/tools/messages.js:24:409)
    at <anonymous>
```

To reproduce:

```bash
git clone -b feature/react-intl git@github.com:kriasoft/react-starter-kit.git
cd react-starter-kit
yarn upgrade babel-plugin-react-intl && yarn messages
```

The issue is thrown by running this transform:

https://github.com/kriasoft/react-starter-kit/blob/feature/react-intl/tools/messages.js#L122-L125

Still investigating a fix, but wanted to log it in case someone else is running into the same issue.

**Comment by WiktorKa** [comment]
Check this out: https://github.com/kriasoft/react-starter-kit/issues/1546#issuecomment-367665401

**Comment by redonkulus** [comment]
From the stack trace its coming from this line: https://github.com/yahoo/babel-plugin-react-intl/blob/master/src/index.js#L203. I'm not sure why, could you add some debugging around this line to see what is missing from the `join`?

**Comment by longlho** [comment]
close due to stale
