### ISSUE TITLE
Cannot find module babel-plugin-react-intl when extracting messages

### ISSUE THREAD

**Issue by MartinCerny-awin** [formatjs/babel-plugin-react-intl#153]
I have upgraded babel to version 7 and react-native to version 0.57.

I get an error when trying to extract messages:
```
$ babel --plugins react-intl src/*
{ Error: Cannot find module 'babel-plugin-react-intl' from '/Volumes/sites/monyl'
- If you want to resolve "react-intl", use "module:react-intl"
    at Function.module.exports [as sync] (/Volumes/sites/monyl/node_modules/resolve/lib/sync.js:43:15)
    at resolveStandardizedName (/Volumes/sites/monyl/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Volumes/sites/monyl/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/Volumes/sites/monyl/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/Volumes/sites/monyl/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/Volumes/sites/monyl/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Volumes/sites/monyl/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Volumes/sites/monyl/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/Volumes/sites/monyl/node_modules/@babel/core/lib/config/config-descriptors.js:63:49) code: 'MODULE_NOT_FOUND' }
```

.babelrc
```
{
  "presets": [
    "module:metro-react-native-babel-preset"
  ],
  "plugins": [
    [
      "react-intl",
      {
        "messagesDir": "./i18n/messages",
        "enforceDescriptions": false
      }
    ]
  ]
}
```

babel packages in package.json
```
    "babel-core": "^7.0.0-bridge.0",
    "@babel/cli": "^7.1.0",
    "@babel/core": "^7.1.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "9.0.0",
    "babel-plugin-react-intl": "3.0.0",
    "react-native": "0.57.0",
    "metro-react-native-babel-preset": "^0.45.3",
```

**Comment by longlho** [comment]
close due to stale
